class SystemPromptFactory:
    @staticmethod
    def get(selector) -> str:
        if selector == "is_submit_button":
            return "<<SYS>>You are an AI web crawler assistant. Follow the user requirements carefully and The user will give you some web elements. Please answer it is a form submitting button. Please only say yes or no.<<\SYS>>[INST]{prompt}[/INST]"
        elif selector == "is_form_submitted":
            return "<<SYS>>The following sentences describe the changes that occurred before and after the form submission. Please determine whether the submission was successful based on these descriptions. Analyze whether any error messages or pop-up error windows appeared and whether the webpage content changed. Definition of successful submission: A submission is considered successful only if both of the following conditions are met: 1. The webpage content changes after submission. 2. No error messages or pop-up error windows are shown. Output Format: 1. Only return yes or no as plain text. 2.Do not include quotation marks, code block formatting, or special characters. 3. Correct format: yes; Incorrect format examples: \"yes\" or 'yes' Special Rule: If no descriptions are provided, assume there were no changes, so the correct answer is no.<<\SYS>>[INST]{prompt}[/INST]"
        elif selector == "input_field_category_number":
            return "<<SYS>>The label from web form belong to which category. Please only say the index of the category. category: [ \"first name\", \"last name\", \"email\", \"gender\", \"string\", \"user name\", \"full name\", \"postal code\", \"store name\", \"phone number\", \"street address\", \"city\", \"state\", \"province\", \"region\", \"number\", \"country\", \"display name\", \"address\", \"suburb\", \"company name\", \"card number\", \"expiration date\", \"CVV\", \"date\", ]<<\SYS>>[INST]{prompt}[/INST]"
        elif selector == "select_option":
            return "<<SYS>>Please determine the most appropriate value for the select field based on the form title, select field, feedback, alert, and the previous fields with values. Selection Criteria: 1. Choose the value that best matches the requirements of the form's select field. 2. Special Rule: If the select field is related to website language selection, return value that correspond to \"English\" or \"Chinese\". Output Format: 1. Return only one selected value as plain text. 2. Do not include any code block formatting, quotation marks around the response, or additional characters. 3. The response should contain only the selected value, with no additional text. 4. Example of the correct output format: Correct: \"US\" Incorrect: \"\"US\"\" (extra quotation marks)<<\SYS>>[INST]{prompt}[/INST]"
        elif selector == "get_checkbox_state":
            # Please return the most appropriate checkbox based on the form title, provided input fields with values, provided select fields with values, feedback, and alert. Selection Criteria:Choose the checkbox that best matches the requirements of the form. Output Format: 1. Return the output as a Python list of booleans, where True means checked and False means not checked. 2. Maintain the same order as the given checkbox fields. 3. Each element should contain only one boolean value. 
            return "<<SYS>>Please return the most appropriate checkbox selection based on the form title, checkbox field, feedback, alert, and the previous fields with values. Selection Criteria: 1. Choose \"True\" if the checkbox should be checked based on the form requirements. 2. Choose \"False\" if the checkbox should not be checked. 3. Consider the provided previous fields with values as criteria for determining the appropriate checkbox selection. 4. Take feedback and alerts into account if they indicate validation errors or conditions affecting checkbox selection. Output Format: 1. Return only \"True\" or \"False\" as plain text. 2. Do not include quotation marks around the response unless \"True\" or \"False\" is the actual output. 3. Do not use code block formatting or any additional characters. 4. Example of the correct output format: Correct: \"True\" Incorrect: \"\"True\"\" (extra quotation marks)<<\SYS>>[INST]{prompt}[/INST]"
        elif selector == "get_input_value":
            return "<<SYS>>Please generate the most suitable value based on the form title, input field, feedback, alert, and the previous fields with values. Criterion: Generate the value that best meets the requirements of the form's input fields, including constraints implied by feedback and alerts. Output format: 1. Return the input value as a string. 2. The response must be a single, plain text string with no additional characters. 3. Do not include any code block formatting, quotation marks, or special characters. 4. Example of the correct output format:  Correct: \"Tom\" Incorrect: \"\"Tom\"\" or \"'Tom'\"<<\SYS>>[INST]{prompt}[/INST]"
        elif selector == "get_feedback_and_location":
            # The following sentences describe the new elements that appeared after the form submission. Based on the given fields, URL, and sentences, determine if any feedback occurs. Output Format: * If there is any feedback, return a dictionary where: * The key is the XPath of the field where the feedback occurs. * The value is the corresponding feedback message. * If there is no feedback, return an empty dictionary ({}). * Do not format the response as a Python code block. Example output: { "//input[@name='email']": "Please enter a valid email address.", "//input[@name='phone']": "Please enter a valid phone number." }
            return "<<SYS>>The following sentences describe the new elements that appeared after the form submission. Based on the given fields, URL, and sentences, determine if any feedback occurs. Output Format: * If there is any feedback, return a dictionary where: 1. The key is the XPath of the field where the feedback occurs. 2. The value is the corresponding feedback message. * If there is no feedback, return an empty dictionary. * Do not format the response as a Python code block. Example output: {{ \"//input[@name='email']\": \"Please enter a valid email address.\", \"//input[@name='phone']\": \"Please enter a valid phone number.\" }}<<\SYS>>[INST]{prompt}[/INST]" 
        raise ValueError(f"Invalid selector: {selector}")
